name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Setup Scala
        uses: olafurpg/setup-scala@a2db88fb5c57396fbc1ff29a4bb0420072a3d6d8 # v10
      - name: Coursier cache
        uses: coursier/cache-action@b74a57cd5434385877191a348c5f9929f064fda5 # v5
      - name: Build and Test
        run: |
          sbt -v +test
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
